export const ActionTypes = {
  //AIRLANESs
  SET_AIRLANES: "SET_AIRLANES",
  CREATE_AIRLANES: "CREATE_AIRLANES",
  SELECTED_AIRLANES: "SELECTED_AIRLANES",
  DELETE_AIRLANES: "DELETE_AIRLANES",
  UPDATE_AIRLANES: "UPDATE_AIRLANES",
  ADD_AIRLANES_PENDING: "ADD_AIRLANES_PENDING",
  GET_AIRLANES_ERROR: "GET_AIRLANES_ERROR",
  REMOVE_SELECTED_AIRLANES: "REMOVE_SELECTED_AIRLANES",

  // user
  USER_REGISTER_PENDING: "USER_REGISTER_PENDING",
  USER_LOGIN_PENDING: "USER_LOGIN_PENDING",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  UPDATE_USER: "UPDATE_USER",

  GET_DETAIL_USER_PENDING: "GET_DETAIL_USER_PENDING",
  GET_DETAIL_USER_SUCCESS: "GET_DETAIL_USER_SUCCESS",
  GET_DETAIL_USER_FAILED: "GET_DETAIL_USER_FAILED",

  //cOUNTRY
  SET_COUNTRY: "SET_COUNTRY",
  CREATE_COUNTRY: "CREATE_COUNTRY",
  SELECTED_COUNTRY: "SELECTED_COUNTRY",
  DELETE_COUNTRY: "DELETE_COUNTRY",
  UPDATE_COUNTRY: "UPDATE_COUNTRY",
  ADD_COUNTRY_PENDING: "ADD_COUNTRY_PENDING",
  GET_COUNTRY_ERROR: "GET_COUNTRY_ERROR",
  REMOVE_SELECTED_COUNTRY: "REMOVE_SELECTED_COUNTRY",
};

export const GET_DETAIL_USER_PENDING = "GET_DETAIL_USER_PENDING";
export const GET_DETAIL_USER_SUCCESS = "GET_DETAIL_USER_SUCCESS";
export const GET_DETAIL_USER_FAILED = "GET_DETAIL_USER_FAILED";

